config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :food_lists
  resources :food_items
  resources :programs do
    resources :days
  end
  get 'welcome/index'

  root 'welcome#index'

end

app/models/food_list.rb
class FoodList < ActiveRecord::Base
  belongs_to :day
  belongs_to :foodItem
  
  enum meals: [:breakfast, :lunch, :dinner, :snack]
  
end

app/controllers/food_lists_controller.rb
class FoodListsController < ApplicationController
  before_action :set_food_list, only: [:show, :edit, :update, :destroy]
  before_action :set_meals
  before_action :set_foods
  
  # GET /food_lists
  # GET /food_lists.json
  def index
    @food_lists = FoodList.all
  end

  # GET /food_lists/1
  # GET /food_lists/1.json
  def show
  end

  # GET /food_lists/new
  def new
    @food_list = FoodList.new
  end

  # GET /food_lists/1/edit
  def edit
  end

  # POST /food_lists
  # POST /food_lists.json
  def create
    @food_list = FoodList.new(food_list_params)

    respond_to do |format|
      if @food_list.save
        format.html { redirect_to @food_list, notice: 'Food list was successfully created.' }
        format.json { render :show, status: :created, location: @food_list }
      else
        format.html { render :new }
        format.json { render json: @food_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_lists/1
  # PATCH/PUT /food_lists/1.json
  def update
    respond_to do |format|
      if @food_list.update(food_list_params)
        format.html { redirect_to @food_list, notice: 'Food list was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_list }
      else
        format.html { render :edit }
        format.json { render json: @food_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_lists/1
  # DELETE /food_lists/1.json
  def destroy
    @food_list.destroy
    respond_to do |format|
      format.html { redirect_to food_lists_url, notice: 'Food list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_list
      @food_list = FoodList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_list_params
      params.require(:food_list).permit(:meal, :day_id, :food_item_id)
    end
    
    def set_meals
      @meals = FoodList.meals
    end  
    
    def set_foods
      @foods = FoodItem.all
    end  
    
end

app/helpers/food_lists_helper.rb
module FoodListsHelper
end

app/views/food_lists/_form.html.erb
<%= form_for(@food_list) do |f| %>
  <% if @food_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_list.errors.count, "error") %> prohibited this food_list from being saved:</h2>

      <ul>
      <% @food_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meal %><br>
    <%= f.select :meal, options_for_select(@meals.collect {|s| [s[0].humanize,
      s[0]]}, selected: @food_list.meal), {} %>
  </div>
  <div class="field">
    <%= f.label :day_id %><br>
    <%= f.text_field :day_id %>
  </div>
  <div class="field">
    <%= f.label :food_item_id %><br>
    <%= f.select :food_item_id, options_for_select(@foods.collect {|a| ["#{a.name}",
      a.id]}, selected: @food_list.food_item_id), {} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_lists/edit.html.erb
<h1>Editing Food List</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_list %> |
<%= link_to 'Back', food_lists_path %>

app/views/food_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Food Lists</h1>

<table>
  <thead>
    <tr>
      <th>Meal</th>
      <th>Day</th>
      <th>Food item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_lists.each do |food_list| %>
      <tr>
        <td><%= food_list.meal %></td>
        <td><%= food_list.day_id %></td>
        <td><%= food_list.food_item_id %></td>
        <td><%= link_to 'Show', food_list %></td>
        <td><%= link_to 'Edit', edit_food_list_path(food_list) %></td>
        <td><%= link_to 'Destroy', food_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food list', new_food_list_path %>

app/views/food_lists/new.html.erb
<h1>New Food List</h1>

<%= render 'form' %>

<%= link_to 'Back', food_lists_path %>

app/views/food_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meal:</strong>
  <%= @food_list.meal %>
</p>

<p>
  <strong>Day:</strong>
  <%= @food_list.day_id %>
</p>

<p>
  <strong>Food item:</strong>
  <%= @food_list.food_item_id %>
</p>

<%= link_to 'Edit', edit_food_list_path(@food_list) %> |
<%= link_to 'Back', food_lists_path %>