config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :food_lists
  resources :food_items
  resources :programs do
    resources :days
  end
  get 'welcome/index'

  root 'welcome#index'

end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :days
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:start_weight, :water_goal, :green_limit, :purple_limit, :red_limit, :yellow_limit, :blue_limit, :orange_limit, :tbsp_limit)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= render 'shared/errors', obj: @program %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@program, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :start_weight %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_field :start_weight, class: "form-control", placeholder: "Starting wieght", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :water_goal %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :water_goal, class: "form-control", placeholder: "Usually half your weight" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :green_limit %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :green_limit, class: "form-control", placeholder: "Green container limit"%>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :purple_limit %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :purple_limit, class: "form-control", placeholder: "Purple container limt" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :red_limit %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :red_limit, class: "form-control", placeholder: "Red container limit" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :yellow_limit %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :yellow_limit, class: "form-control", placeholder: "Yellow container limit" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :blue_limit%>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :blue_limit, class: "form-control", placeholder: "Blue container limit" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :orange_limit %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :orange_limit, class: "form-control", placeholder: "Orange container limit" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :tbsp_limit %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :tbsp_limit, class: "form-control", placeholder: "Tablespoon limit" %>
        </div>
      </div>
      <br>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-md' %>
        </div>
      </div>
    <% end %>
    <div align="center">
      [ <%= link_to 'Return to programs list', programs_path %> ]
    </div>
</div>
</div>

app/views/programs/edit.html.erb
<h1 align="center">Editing Program</h1>

<%= render 'form' %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Your Programs</h1>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Weight</th>
        <th>Water</th>
        <th><div class="green_container" id="tuperware_header"></div></th>
        <th><div class="purple_container" id="tuperware_header"></div></th>
        <th><div class="red_container" id="tuperware_header"></div></th>
        <th><div class="yellow_container" id="tuperware_header"></div></th>
        <th><div class="blue_container" id="tuperware_header"></div></th>
        <th><div class="orange_container" id="tuperware_header"></div></th>
        <th><div class="tbsp_container" id="tuperware_header"></div></th>
        
      </tr>
    </thead>
  
    <tbody>
         <% @programs.each do |program| %>
        <tr>
          <td><%= link_to program.id, program_path(program) %></td>
          <td><%= program.start_weight %></td>
          <td><%= program.water_goal %></td>
          <td><%= program.green_limit %></td>
          <td><%= program.purple_limit %></td>
          <td><%= program.red_limit %></td>
          <td><%= program.yellow_limit %></td>
          <td><%= program.blue_limit %></td>
          <td><%= program.orange_limit %></td>
          <td><%= program.tbsp_limit %></td>
          <td><button type="button" class="btn btn-default"><%= link_to 'Destroy', program, method: :delete, 
            data: { confirm: 'Are you sure?' } %></button></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class=" col-sm-10">
    <a href= <%= new_program_path %> class="btn btn-primary btn active" role="button">New Program</a>
</div>

app/views/programs/new.html.erb
<h1 align="center">New Program</h1>

<%= render 'form' %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
   <div class="panel-heading">
      <strong>Program Details</strong>
      <div class="start_weight">
        <strong>Start weight: </strong>
        <%= @program.start_weight %>
      </div>
  </div>
  <div class="panel-body">
    <strong>Daily Container Limits</strong>
     <div>
        <div class="green_container" id="tuperware">
        <strong><%= @program.green_limit %></strong>
        </div>
      </div>
     <div>
        <div class="purple_container" id="tuperware">
        <strong><%= @program.purple_limit %></strong>
        </div>
      </div> 
      <div>
        <div class="red_container" id="tuperware">
        <strong><%= @program.red_limit %></strong>
        </div>
      </div>
      <div>
        <div class="yellow_container" id="tuperware">
        <strong><%= @program.yellow_limit %></strong>
        </div>
      </div>
     <div>
        <div class="blue_container" id="tuperware">
        <strong><%= @program.blue_limit %></strong>
        </div>
      </div>
     <div>
        <div class="orange_container" id="tuperware">
        <strong><%= @program.orange_limit %></strong>
        </div>
      </div> 
      <div>
        <div class="tbsp_container" id="tuperware">
        <strong><%= @program.tbsp_limit %></strong>
        </div>
      </div>
</div>
    <div class="panel-footer">
        <a href=<%= programs_path %> class="btn btn-primary btn-sm active" role="button">Back</a>
        <a href=<%= edit_program_path(@program) %> class="btn btn-primary btn-sm active" role="button">Edit Program</a>
    </div>
</div>

<h1>Program Days</h1>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Weight</th>
        <th>Water</th>
        <th><div class="green_container" id="tuperware_header"></div></th>
        <th><div class="purple_container" id="tuperware_header"></div></th>
        <th><div class="red_container" id="tuperware_header"></div></th>
        <th><div class="yellow_container" id="tuperware_header"></div></th>
        <th><div class="blue_container" id="tuperware_header"></div></th>
        <th><div class="orange_container" id="tuperware_header"></div></th>
        <th><div class="tbsp_container" id="tuperware_header"></div></th>
        
      </tr>
    </thead>
  
    <tbody>
         <% @program.days.each do |day| %>
        <tr>
          <td><%= link_to day.id, program_day_path(@program.id, day) %></td>
          <td><%= day.weight %></td>
          <td><%= day.water_consumed %></td>
          <td><%= day.green_used %></td>
          <td><%= day.purple_used %></td>
          <td><%= day.red_used %></td>
          <td><%= day.yellow_used %></td>
          <td><%= day.blue_used %></td>
          <td><%= day.orange_used %></td>
          <td><%= day.tbsp_used %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class=" col-sm-10">
    <a href=<%= new_program_day_path(@program.id) %> class="btn btn-primary btn active" role="button">Add Day</a>
</div>