config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :food_lists
  resources :food_items
  resources :programs do
    resources :days
  end
  get 'welcome/index'

  root 'welcome#index'

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :program
  has_many :food_lists
  has_many :food_items, :through => :food_lists, :source => :food_lists
  
   validates :weight, presence: true, 
        numericality: {greater_than_or_equal_to: 0}
  
  enum workout: [:i_did_not_workout, :total_body_cardio_fix, :upper_fix, :lower_fix, 
        :pilates_fix, :cardio_fix, :dirty_30, :yoga_fix, :plyo_fix]
  
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_days
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :set_workouts
  before_action :set_foods

  # GET programs/1/days
  def index
    @days = @program.days
  end

  # GET programs/1/days/1
  def show
  end

  # GET programs/1/days/new
  def new
    @day = @program.days.build
  end

  # GET programs/1/days/1/edit
  def edit
  end

  # POST programs/1/days
  def create
    @day = @program.days.build(day_params)

    if @day.save
      redirect_to([@day.program, @day], notice: 'Day was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT programs/1/days/1
  def update
    if @day.update_attributes(day_params)
      redirect_to([@day.program, @day], notice: 'Day was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE programs/1/days/1
  def destroy
    @day.destroy

    redirect_to program_days_url(@program)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_days
      @program = Program.find(params[:program_id])
    end

    def set_day
      @day = @program.days.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def day_params
      params.require(:day).permit(:weight, :workout, :water_consumed, :green_used, :purple_used, :red_used, :yellow_used, :blue_used, :orange_used, :tbsp_used)
    end
    
    def set_workouts
      @workouts = Day.workouts
    end
    
    def set_foods
      @foods = FoodItem.all
    end  
    
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_day.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
      <strong>Day <%= @day.id %></strong>
      <div class="start_weight">
        <strong>Weight: </strong>
        <%= @day.weight %>
      </div>
  </div>
  <div class="panel-body">
    <strong>Containers Used</strong>
     <div>
        <div class="green_container" id="tuperware">
        <strong><%= @day.green_used %></strong>
        </div>
      </div>
     <div>
        <div class="purple_container" id="tuperware">
        <strong><%= @day.purple_used %></strong>
        </div>
      </div> 
      <div>
        <div class="red_container" id="tuperware">
        <strong><%= @day.red_used %></strong>
        </div>
      </div>
      <div>
        <div class="yellow_container" id="tuperware">
        <strong><%= @day.yellow_used %></strong>
        </div>
      </div>
     <div>
        <div class="blue_container" id="tuperware">
        <strong><%= @day.blue_used %></strong>
        </div>
      </div>
     <div>
        <div class="orange_container" id="tuperware">
        <strong><%= @day.orange_used %></strong>
        </div>
      </div> 
      <div>
        <div class="tbsp_container" id="tuperware">
        <strong><%= @day.tbsp_used %></strong>
        </div>
      </div>
</div>
  <div class="panel-footer">
      <a href=<%= program_path(@day.program) %> class="btn btn-primary btn-sm active" role="button">Back</a>
      <a href=<%=  edit_program_day_path(@day.program, @day) %> class="btn btn-primary btn-sm active" role="button">Edit Program</a>
    </div>
</div>

<h3>Today's Foods</h3>

<% @foods.each do |food| %>
      
  <div class="well well-sm">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-2">
          <div class="green_container" id="big-tuperware"><%= food.container_value %></div>
        </div>
        <div class="col-xs-2">
          <h4><%= food.name %></h4>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/days/_form.html.erb
  
  <%= render 'shared/errors', obj: @day %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for([@day.program, @day], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :weight %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_field :weight, class: "form-control", placeholder: "Today's wieght", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :workout %>
        </div>
        <div class='col-sm-10'>
          <%= f.select :workout, options_for_select(@workouts.collect {|s| [s[0].humanize,
            s[0]]}, selected: @day.workout), {}, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :water_consumed %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :water_consumed, class: "form-control", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :green_used %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :green_used, class: "form-control", placeholder: "Green containers used", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :purple_used %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :purple_used, class: "form-control", placeholder: "Purple containers used", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :red_used %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :red_used, class: "form-control", placeholder: "Red containers used", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :yellow_used %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :yellow_used, class: "form-control", placeholder: "Yellow containers used", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :blue_used %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :blue_used, class: "form-control", placeholder: "Blue containers used", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :orange_used %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :orange_used, class: "form-control", placeholder: "Orange containers used", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :tbsp_used %>
        </div>
        <div class='col-sm-10'>
          <%= f.number_field :tbsp_used, class: "form-control", placeholder: "Tablespoos used", autofocus: true %>
        </div>
      </div>
      <br>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-md' %>
        </div>
      </div>
    <% end %>
    <div align="center">
      [ <%= link_to 'Return to current day', [@day.program, @day] %> ]
    </div>
</div>
</div>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <tr>
    <th>Weight</th>
    <th>Workout</th>
    <th>Water consumed</th>
    <th>Green used</th>
    <th>Purple used</th>
    <th>Red used</th>
    <th>Yellow used</th>
    <th>Blue used</th>
    <th>Orange used</th>
    <th>Tbsp used</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @days.each do |day| %>
  <tr>
    <td><%= day.weight %></td>
    <td><%= day.workout %></td>
    <td><%= day.water_consumed %></td>
    <td><%= day.green_used %></td>
    <td><%= day.purple_used %></td>
    <td><%= day.red_used %></td>
    <td><%= day.yellow_used %></td>
    <td><%= day.blue_used %></td>
    <td><%= day.orange_used %></td>
    <td><%= day.tbsp_used %></td>
    <td><%= link_to 'Show', [day.program, day] %></td>
    <td><%= link_to 'Edit', edit_program_day_path(day.program, day) %></td>
    <td><%= link_to 'Destroy', [day.program, day], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Day', new_program_day_path(params[:program_id]) %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'day' %>