config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :food_lists
  resources :food_items
  resources :programs do
    resources :days
  end
  get 'welcome/index'

  root 'welcome#index'

end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
 <div class="container">
     <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=
        ".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Fix Tracker</a>
     </div> <!-- end div class="navbar-header" -->
 <div class="collapse navbar-collapse">
     <ul class="nav navbar-nav">
      <li ><%= link_to "Programs", programs_path %></li>
      <li ><%= link_to "Foods", food_items_path %></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Devs", developers_path %></li>
     </ul>
     </div> <!-- end div class="collapse navbar-collapse" -->
 </div> <!-- end div class="container" -->
 
</div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

  <div id='container'>
    <%= yield %>
  </div>
</body>
</html>